# Install the pg driver:
#   gem install pg

# Configure your database.yml as follows:

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

development:
  <<: *default
  database: TeamViewer_development

test:
  <<: *default
  database: TeamViewer_test

production:
  <<: *default
  database: TeamViewer_production
  url: <%= ENV['DATABASE_URL'] %>
