# Install the pg driver:
#   gem install pg

# Configure your database.yml as follows:

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

development:
  <<: *default
  database: TeamViewer_development
  url: <%= ENV['DEV_DATABASE_URL'] %>

test:
  <<: *default
  database: TeamViewer_test
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
  database: TeamViewer_production
  url: <%= ENV['DATABASE_URL'] %>
